CONFIGS = {
    "mutag": {
        "path": "data/mutag/full.jsonl",
        "in_dim": 7,
        "hidden_dim": 64,
        "out_dim": 64,
        "num_layers": 3,
        "epochs": 50,
        "n_tables": 10,
        "n_funcs": 4,
        "w": 1.0,
        "k": 5,
    },
    "proteins": {
        "path": "data/proteins/full.jsonl",
        "in_dim": 3,
        "hidden_dim": 64,
        "out_dim": 64,
        "num_layers": 3,
        "epochs": 50,
        "n_tables": 10,
        "n_funcs": 4,
        "w": 1.0,
        "k": 5,
    },
    "imdb-binary": {
        "path": "data/imdb-binary/full.jsonl",
        "in_dim": 31,
        "hidden_dim": 64,
        "out_dim": 64,
        "num_layers": 3,
        "epochs": 50,
        "n_tables": 10,
        "n_funcs": 4,
        "w": 1.0,
        "k": 5,
    },
    "aids": {
        "path": "data/aids/full.jsonl",
        "in_dim": 38,
        "hidden_dim": 64,
        "out_dim": 64,
        "num_layers": 3,
        "epochs": 50,
        "n_tables": 10,
        "n_funcs": 4,
        "w": 1.0,
        "k": 5,
    },
}